### PR TITLE
Remove the legacy Gradle build lifecycle API

### LINKED ISSUE #148: configuration-cache enabled builds fail due to buildFinished API
The styled build does not have any capability of Listener API.

https://discuss.gradle.org/t/gradle-configuration-cache-gradle-addlistener-is-unsupported/38691

### PR DESCRIPTION
**Pull request by jmatsu**
Related to #147 and #148

As for buildFinished, we have not used this action for a while. We can safely delete this.

### CODE REVIEW

File: src/main/groovy/com/deploygate/gradle/plugins/tasks/UploadArtifactTask.groovy [hunk 1]
```diff
@@ -116,12 +116,9 @@ abstract class UploadArtifactTask extends DefaultTask {
             if (!sent && (Config.shouldOpenAppDetailAfterUpload() || response.typedResponse.application.revision == 1)) {
                 BrowserUtils.openBrowser "${project.deploygate.endpoint}${response.typedResponse.application.path}"
             }
-        } catch (HttpResponseException e) {
+        } catch (Throwable e) {
```
Comment (satsukies) [inline src/main/groovy/com/deploygate/gradle/plugins/tasks/UploadArtifactTask.groovy:119]: I understand to this change behavior to send to server always.
So, I ask to reason to why aggregate to super class.

**Review by satsukies — CHANGES_REQUESTED** [review]
please check my comments, thanks.

File: src/main/groovy/com/deploygate/gradle/plugins/tasks/UploadArtifactTask.groovy (hunk 1 above)
Comment (jmatsu) [reply src/main/groovy/com/deploygate/gradle/plugins/tasks/UploadArtifactTask.groovy:119]: We never allow any failure when notifying lifecycle events to the server so it's better to suppress Throwable rather than specifying specific exceptions.

Comment (satsukies) [reply src/main/groovy/com/deploygate/gradle/plugins/tasks/UploadArtifactTask.groovy:119]: OK, I understand to this change is necessary 👍

**Review by satsukies — APPROVED** [review]
LGTM 🙆‍♂️

**Comment by jmatsu** [comment]
Thank you so much!
